openapi: 3.0.3
info:
  title: Diversion Core API
  description: Definition of the Core API used to access low-level functionality of Diversion
  version: 0.2.0
servers:
  - url: https://api.diversion.dev/v0
    description: Base endpoint

paths:
  /auth/complete:
    get:
      operationId: src.handlers.auth.complete
      description: Callback URL for sign-ins
      tags:
        - Authentication
  /auth/poll:
    get:
      operationId: src.handlers.auth.poll
      description: Polling endpoint for the CLI to wait for the user to complete the sign-in flow
      tags:
        - Authentication
  /auth/fetch_code:
    get:
      operationId: src.handlers.auth.fetch_code
      description: Retrieve the code grant in exchange for the correct code challenge and verifier
      tags:
        - Authentication
  /auth/test:
    get:
      operationId: src.handlers.auth.test_token
      summary: Test token validity, repo write access
      description: Validate the given auth token, test write access to specified repo
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Authentication
  /repos:
    post:
      operationId: src.handlersv2.repo.post
      summary: Create a repo
      description: Create an empty repo
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Management
    get:
      operationId: src.handlersv2.repo.list_all
      summary: List user's repositories
      description: Get a list of repositories accessibly by the authenticated user
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Management
  /repos/{repo_id}:
    get:
      operationId: src.handlersv2.repo.get
      summary: Get details of an existing repo.
      description: Get details of an existing repo.
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
    delete:
      operationId: src.handlersv2.repo.delete
      summary: Delete a repo.
      description: >-
        Delete a repo. All files, workspaces, commits, branches permissions etc. associated with the
        repo will be deleted.
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
  /repos/{repo_id}/import:
    post:
      operationId: src.handlers.integrations.git_import.import_in_background
      summary: Import a Git repo into this Diversion repo
      description: >-
        Import a Git repo with all history from a Git URL.
        `repo_id` must have no commits and no branches, or be already marked as synced with the same `git_url`.
        The git repo URL must have http credentials embedded or otherwise hosted on Github and the owner has the Diversion Github app integration set up.
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
  /repos/import/check:
    post:
      operationId: src.handlers.integrations.git_import.import_verify_url
      summary: Check if a git repo could be imported to Diversion
      description: >-
        The git repo URL must have http credentials embedded or otherwise hosted on Github and the owner has the Diversion Github app integration set up.
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Repository Manipulation
  /repos/{repo_id}/sync:
    post:
      operationId: src.handlers.integrations.github.handle_repo_github_webhook
      summary: Sync a Git repo to this Diversion repo
      description: Sync all history from Git. The repo must already be associated with a Git repo (see import).
      tags:
        - Repository Manipulation
  /repos/{repo_id}/commits:
    get:
      operationId: src.handlersv2.commit.list_all
      description: Get a list of commits
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Commit Manipulation
  /repos/{repo_id}/commits/bulk:
    get:
      operationId: src.handlersv2.commit.get_bulk
      description: Get bulk details of commits by their IDs
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Repository Commit Manipulation
  /repos/{repo_id}/commits/{commit_id}:
    get:
      operationId: src.handlersv2.commit.get
      description: Get details of a specific commit
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Repository Commit Manipulation
  /repos/{repo_id}/workspaces:
    post:
      operationId: src.handlersv2.workspace.create_workspace
      summary: Create a workspace
      description: Create a new workspace
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation
    get:
      operationId: src.handlersv2.workspace.list_all_workspaces
      description: List user's workspaces
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation
  /repos/{repo_id}/workspaces/{workspace_id}:
    get:
      operationId: src.handlersv2.workspace.get_workspace
      description: Get a workspace object details
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation
  /repos/{repo_id}/workspaces/{workspace_id}/rename:
    post:
      operationId: src.handlersv2.workspace.rename_workspace
      summary: Update workspace name
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation
  /repos/{repo_id}/workspaces/{workspace_id}/checkout:
    post:
      operationId: src.handlersv2.workspace.checkout
      summary: Workspace checkout ref
      description: >-
        Set the workspace to follow a different branch or commit (checkout).
        Currently supports only moving to a branch with an identical commit as the workspace's current branch,
        or moving to any branch/commit if the workspace has no working changes.
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation
  /repos/{repo_id}/workspaces/{workspace_id}/updates:
    get:
      operationId: src.handlersv2.workspace.get_workspace_updates
      summary: Get updates needed to be applied by the client to this workspace
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation

  /repos/{repo_id}/workspaces/{workspace_id}/status:
    get:
      operationId: src.handlersv2.workspace.get_status
      summary: Get status of changes in workspace
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation

  /repos/{repo_id}/workspaces/{workspace_id}/reset:
    post:
      operationId: src.handlersv2.workspace.reset
      summary: Reset changes in workspace
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation

  /repos/{repo_id}/workspaces/{workspace_id}/forward:
    post:
      operationId: src.handlersv2.workspace.forward_workspace
      summary: Merge base branch into workspace
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation

  /repos/{repo_id}/workspaces/{workspace_id}/commit:
    post:
      operationId: src.handlersv2.workspace.commit_workspace
      description: Commit workspace to base branch
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Commit Manipulation

  /repos/{repo_id}/workspaces/{workspace_id}/preferences:
    get:
      operationId: src.handlersv2.workspace.get_preferences
      summary: Get preferences of the current user
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Repository Workspace Manipulation
    put:
      operationId: src.handlersv2.workspace.set_preferences
      summary: Update the preferences of the current user
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Workspace Manipulation

  /repos/{repo_id}/workspaces/{workspace_id}/other_statuses:
    get:
      operationId: src.handlersv2.workspace.get_other_statuses
      summary: Get list of potential clashes with files in other users' workspaces and branches
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Repository Workspace Manipulation

  /repos/{repo_id}/branches:
    post:
      operationId: src.handlersv2.branch.post
      description: Create a branch
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Branch Manipulation
    get:
      operationId: src.handlersv2.branch.list_all
      description: Get a list of all branches in the repo.
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Branch Manipulation
  /repos/{repo_id}/branches/{branch_id}:
    patch:
      operationId: src.handlersv2.branch.patch
      summary: Update a branch
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Branch Manipulation
    get:
      operationId: src.handlersv2.branch.get
      summary: Get the current branch details
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Branch Manipulation
    delete:
      operationId: src.handlersv2.branch.delete
      description: Delete a branch
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Branch Manipulation
  /repos/{repo_id}/tags:
    get:
      operationId: src.handlersv2.tag.list_all
      summary: Get a list of all tags in the repo.
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Tag Manipulation
    post:
      operationId: src.handlersv2.tag.post
      summary: Create a tag
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Tag Manipulation
  /repos/{repo_id}/tags/{tag_id}:
    get:
      operationId: src.handlersv2.tag.get
      summary: Get tag details
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Tag Manipulation
    patch:
      operationId: src.handlersv2.tag.patch
      summary: Update a tag
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Tag Manipulation
    delete:
      operationId: src.handlersv2.tag.delete
      summary: Delete a tag
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Tag Manipulation

  /repos/{repo_id}/shelves:
    get:
      operationId: src.handlersv2.shelf.list_all
      summary: Get a list of all shelves in the repo.
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Shelves Manipulation
    post:
      operationId: src.handlersv2.shelf.post
      summary: Create a shelf
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Shelves Manipulation
  /repos/{repo_id}/shelves/{shelf_id}:
    get:
      operationId: src.handlersv2.shelf.get
      summary: Get shelf details
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Shelves Manipulation
    delete:
      operationId: src.handlersv2.shelf.delete
      summary: Delete a shelf
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Shelves Manipulation
  /repos/{repo_id}/shelves/{shelf_id}/apply:
    post:
      operationId: src.handlersv2.shelf.apply
      summary: Apply a shelf onto a workspace
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Shelves Manipulation

  /repos/{repo_id}/trees/{ref_id}:
    get:
      operationId: src.handlersv2.tree.filetree
      summary: Get file tree snapshot. Either one of workspace, branch or commit ID needs to be specified as ref ID.
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
  /repos/{repo_id}/trees/{ref_id}/{path}:
    get:
      operationId: src.handlersv2.tree.filetree_under_path
      summary: Get file tree snapshot for a nested tree path. Either one of workspace, branch or commit ID needs to be specified as ref ID.
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
  /repos/{repo_id}/files/history/{ref_id}/{path}:
    get:
      operationId: src.handlersv2.commit.get_object_history
      summary: Get object history in a ref by its latest path
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
  /repos/{repo_id}/files/{ref_id}/{path}:
    get:
      operationId: src.handlersv2.files.get_file_entry
      summary: Get file entry (either tree or blob). Either one of workspace, branch or commit ID needs to be specified.
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation
    post:
      operationId: src.handlersv2.files.create_or_update_file
      summary: Upload file to a new or existing path
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - File Mutation
    delete:
      operationId: src.handlersv2.files.delete_file
      summary: Delete a file from an existing path
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - File Mutation
    patch:
      operationId: src.handlersv2.files.move_file
      summary: Move a file to a different path
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - File Mutation

  /repos/{repo_id}/blobs/{ref_id}/{path}:
    get:
      operationId: src.handlersv2.files.get_blob
      summary: Get blob contents snapshot. Either one of workspace, branch or commit ID needs to be specified.
      #        Can't define more content-types because of this bug: https://github.com/zalando/connexion/issues/1062
      #        default:
      #          $ref: '#/components/responses/Error'
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation

  /repos/{repo_id}/blobs/download:
    get:
      operationId: src.handlersv2.files.download_blob
      summary: Get blob contents using storage information, as retrieved from other APIs.
      #        Can't define more content-types because of this bug: https://github.com/zalando/connexion/issues/1062
      #        default:
      #          $ref: '#/components/responses/Error'
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Manipulation

  /repos/{repo_id}/blobs/upload:
    get:
      operationId: src.handlersv2.files.get_blob_upload_link
      summary: Request an upload link for async blob upload from client side
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - File Mutation

  /repos/{repo_id}/merges/{merge_id}:
    get:
      operationId: src.handlersv2.merge.get_open_merge
      summary: Details of a specific merge in progress
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation
    post:
      operationId: src.handlersv2.merge.finalize
      summary: After all conflicts are resolved, finalizes the merge with a commit
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation

  /repos/{repo_id}/merges/{merge_id}/close:
    post:
      operationId: src.handlersv2.merge.close_merge
      summary: Close an open merge without resolving it
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation
  /repos/{repo_id}/merges/{merge_id}/conflicts/{conflict_id}/accept:
    post:
      operationId: src.handlersv2.merge.accept_side
      summary: Accepts a change from one of the branches (base or other)
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation
  /repos/{repo_id}/merges/{merge_id}/conflicts/{conflict_id}:
    post:
      operationId: src.handlersv2.merge.set_result
      summary: Update a conflicting file, potentially resolving the conflict.
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation
  /repos/{repo_id}/merges:
    get:
      operationId: src.handlersv2.merge.list_open_merges
      summary: Retrieve conflicted merges in this repo
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation
    post:
      operationId: src.handlersv2.merge.post
      summary: Merge ref into a branch
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Merge Manipulation
  /repos/{repo_id}/revert:
    post:
      operationId: src.handlersv2.revert.revert
      summary: Revert commit
      description: >
        The operation reverts any changes done in the single commit represented by revert_ref_id (compared to its own parent).
        These opposing changes are then applied into the branch represented by base_id.
        If any changes were done between revert_ref_id and base_id, they will be checked for conflicts with the revert changes.
      security:
        - OAuth2:
            - coreapi/write
      tags:
        - Repository Commit Manipulation
  /repos/{repo_id}/collaborators:
    get:
      operationId: src.handlers.collaboration.list_collaborators
      description: Get all collaborators and pending invites for repo
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Collaborators
  /repos/{repo_id}/collaborators/{user_id}:
    patch:
      operationId: src.handlers.collaboration.update_mode
      description: Change a user's access level to the repo
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Collaborators
    delete:
      operationId: src.handlers.collaboration.revoke_access
      description: Revoke a user's access level to the repo
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Collaborators
  /repos/{repo_id}/invites:
    put:
      operationId: src.handlersv2.invites.create_new
      description: Invite a collaborator to a repository
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Collaborators
  /repos/{repo_id}/invites/{invite_id}:
    post:
      operationId: src.handlersv2.invites.resend
      description: Resend existing invite
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Collaborators
    delete:
      operationId: src.handlersv2.invites.revoke
      description: Revoke existing invite
      security:
        - OAuth2:
            - coreapi/read
        - OAuth2:
            - coreapi/write
      tags:
        - Collaborators
  /repos/{repo_id}/compare:
    get:
      operationId: src.handlersv2.tree.compare
      summary: Compare two refs (commit/branch/workspace/tag/tree) in this repo
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Repository Content Comparison
  /debug/isalive:
    get:
      operationId: src.handlers.debug.is_alive
      summary: Check server is alive
      tags:
        - Debug
  /support/bundle/upload:
    get:
      operationId: src.handlers.support.get_support_bundle_upload_link
      summary: Get a presigned url that will be used to upload a support bundle
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Support
  /analytics/ingest:
    post:
      operationId: src.handlers.analytics.ingest
      summary: Ingest analytics events
      security:
        - OAuth2:
            - coreapi/read
      tags:
        - Analytics
  /analytics/anonymous/ingest:
    post:
      operationId: src.handlers.analytics.ingest_anon
      summary: Ingest analytics events without user context
      tags:
        - Analytics
  /integrations/github:
    post:
      operationId: src.handlers.integrations.github.handle_github_app_webhook
      summary: An endpoint for Github app installation callbacks
      description: Used for app installation events along with webhooks events used for repo sync.
      tags:
        - Github App Integration
components:
  securitySchemes:
    OAuth2: # arbitrary name
      type: oauth2
      x-tokenInfoFunc: src.token_info.token_auth
      description: This API uses OAuth 2 with the implicit grant flow
      flows:
        implicit:
          authorizationUrl: https://auth.diversion.dev/oauth2/authorize
          scopes:
            coreapi/read: Operations with no possible side-effects
            coreapi/write: Modifying operations
            coreapi/admin: Organizational operations like adding a repo or changing repo properties